### ISSUE TITLE
Port to Gtk+3

### ISSUE THREAD

**Issue by yell0wfl4sh** [sugarlabs/falabracman-activity#1]
WIP: https://github.com/yashagrawal3/falabracman-activity/tree/gtk3

**Comment by Aniket21mathur** [comment]
@yashagrawal3  is there any need to keep this issue open anymore?
Thanks!

**Comment by rhl-bthr** [comment]
Thanks, fixed in 1d8fee0fa216abd20c685e0c97eb5166c433539c
