### ISSUE TITLE
Port from GStreamer Gst.Message.structure to get_structure()

### ISSUE THREAD

**Issue by rhl-bthr** [sugarlabs/falabracman-activity#4]
See description of https://github.com/orgs/sugarlabs/projects/3 for reference

**Comment by tonadev** [comment]
Hi, I noticed that this issue has been solved and closed. However it stills appears at Google Code In Tasks

**Comment by rhl-bthr** [comment]
Thanks for letting us know.
Also, please open issues for any other such instances you come across
