### ISSUE TITLE
Port to python 3.

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/falabracman-activity#9]

**Comment by carpecodeum** [comment]
would like to work on this!

**Comment by quozl** [comment]
Welcome.  Thanks.  We don't ask to work on things here at Sugar Labs, we just work on them ... see our [Guide to Contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#contributing).

@srevinsaju missed adding a link back to this issue on pull request https://github.com/sugarlabs/falabracman-activity/pull/10 but may want some help.  Get involved in review.  See our [Guide for Reviewers](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#guide-for-reviewers).

**Comment by srevinsaju** [comment]
Forgot to mention this on the PR. Closed by https://github.com/sugarlabs/falabracman-activity/pull/11
